---
title: "Cat Project Analysis"
author: "Group-A: Josh and Olivia"
date: "2/19/25"
output:
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r, setup, include=FALSE}
require(dplyr)
require(mosaic)   # Load additional packages here 
require(Amelia)

# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r}
cats <- read.csv("http://pmatheson.people.amherst.edu/CatsSet.csv")
```

``` {r}
#Get rid of pesky NA's in quantitative sets and replace with the average
cats$Age[is.na(cats$Age)] <- mean(cats$Age,na.rm=T)
cats$Weight..lbs.[is.na(cats$Weight..lbs.)] <- mean(cats$Weight..lbs.,na.rm=T)
cats$pH[is.na(cats$pH)] <- mean(cats$pH,na.rm=T)
cats$BG[is.na(cats$BG)] <- mean(cats$BG,na.rm=T)
cats$iCa[is.na(cats$iCa)] <- mean(cats$iCa,na.rm=T)
cats$K[is.na(cats$K)] <- mean(cats$K,na.rm=T)
cats$Lac[is.na(cats$Lac)] <- mean(cats$Lac,na.rm=T)
cats$BUN[is.na(cats$BUN)] <- mean(cats$BUN,na.rm=T)
cats$Creat[is.na(cats$Creat)] <- mean(cats$Creat,na.rm=T)
cats$TS[(cats$TS)=="No bloodwork"] <- NA
cats$PCV[(cats$PCV)=="No bloodwork"] <- NA
cats$TS[(cats$TS)==""] <- NA
cats$PCV[(cats$PCV)==""] <- NA
cats$PCV<-as.numeric(cats$PCV)
cats$TS<-as.numeric(cats$TS)
cats$PCV[is.na(cats$PCV)] <- mean(cats$PCV,na.rm=T)
cats$TS[is.na(cats$TS)] <- mean(cats$TS,na.rm=T)
cats$Temp[is.na(cats$Temp)] <- mean(cats$Temp,na.rm=T)
cats$HR[is.na(cats$HR)] <- mean(cats$HR,na.rm=T)
cats$Urine.protein[(cats$Urine.protein)=="Not checked"] <- NA
cats$Urine.protein<-as.numeric(cats$Urine.protein)
cats$Urine.protein[is.na(cats$Urine.protein)] <- mean(cats$Urine.protein,na.rm=T)
cats$USG[(cats$USG)=="Not checked"] <- NA
cats$USG<-as.numeric(cats$USG)
cats$USG[is.na(cats$USG)] <- mean(cats$USG,na.rm=T)
cats$Urine.pH[(cats$Urine.protein)=="Not checked"] <- NA
cats$Urine.pH<-as.numeric(cats$Urine.pH)
cats$Urine.pH[is.na(cats$Urine.pH)] <- mean(cats$Urine.pH,na.rm=T)

cats$Diet[(cats$Diet=="DRY")] <- "Dry"
cats$Diet[(cats$Diet=="Unknown")] <- "Dry"
cats$Access.to.outdoors.[(cats$Access.to.outdoors.=="Unknonw")] <- "No"
cats$Access.to.outdoors.[(cats$Access.to.outdoors.=="Unknown")] <- "No"
cats$Stress[(cats$Stress=="Unknown")] <- "No"
cats$Previous.FLUTD.signs.[(cats$Previous.FLUTD.signs.=="Unknown")] <- "Yes"
cats$Vx.[(cats$Vx.=="Unknown")] <- "Yes"
cats$PMHx[(cats$PMHx=="Unknown")] <- "No"

cats$Size.of.u.cath[(cats$Size.of.u.cath=="Slippery Sam")] <- 3.5
cats$Flush.[(cats$Flush.=="Unknown")] <- "Yes"
cats$Bolus.[(cats$bolus=="Unknown")] <- "Yes"
cats$Severe.illness.[(cats$Severe.illness.=="Undetermined")] <- "No"

cats$Anemia.[(cats$Anemia.=="Not checked")] <- "No"
cats$Became.anemic.[(cats$Became.anemic.=="Not rechecked")] <- "No"
cats$Became.anemic.[(cats$Became.anemic.=="No bloodwork")] <- "No"
cats$Crystals[(cats$Crystals=="Not checked")] <- "Yes"
cats$Urine.WBC[(cats$Urine.WBC=="Not checked")] <- NA
cats$Urine.RBC[(cats$Urine.RBC=="Not checked")] <- NA


data2<-na.omit(cats) #work with this data - doesn't have any N/As
```

```{r}
CatDatasetCreat <- cats %>%
  mutate(Ket = ifelse(Ketamine== "Yes", 1, 0)) %>%
  mutate(Val = ifelse(Valium=="Yes", 1, 0)) %>%
  mutate(Opi = ifelse(Opioid== "Yes", 1, 0)) %>%
  mutate(Dex = ifelse(Dexmedetomidine=="Yes", 1, 0)) %>%
  mutate(Iso = ifelse(Isoflurane=="Yes", 1, 0)) %>%
  mutate(Prop = ifelse(Propofol=="Yes", 1, 0)) %>%
  rename(RepeatUO="Repeat.UO.")%>%
  rename(Survival30="Survival.30.day")%>%
  rename(FLUTD="Previous.FLUTD.signs.")%>%
  rename(HospUO="Re.UO.in.hosp")%>%
  rename(PrevUO="Previous.UO")%>%
  rename(Flush="Flush.")%>%
  rename(Bolus="Bolus.")%>%
  rename(hrsCath="Hrs.of.cath")%>%
  rename(cathSize="Size.of.u.cath")%>%
  filter(!is.na(cathSize)) %>%
  filter(!is.na(  hrsCath)) %>%
  filter(!is.na( RepeatUO)) %>%
  filter(!is.na( Survival30)) %>%
  filter(!is.na( FLUTD)) %>%
  filter(!is.na( PrevUO)) %>%
  filter(!is.na( Flush)) %>%
  filter(!is.na(Bolus)) %>%
  filter(!is.na( HospUO )) %>%
  select(cathSize,  hrsCath, RepeatUO, Survival30, FLUTD, PrevUO, Flush, Bolus, HospUO ,Ket, Val, Opi, Dex, Iso, Prop)
CatDatasetCreat$RepeatUO <- ifelse(CatDatasetCreat$RepeatUO == "Yes", 1, ifelse(CatDatasetCreat$RepeatUO == "No", 0,2))
CatDatasetCreat$Survival30 <- ifelse(CatDatasetCreat$Survival30 == "Yes", 1, ifelse(CatDatasetCreat$Survival30 == "No", 0,2))
CatDatasetCreat$FLUTD <- ifelse(CatDatasetCreat$FLUTD == "Yes", 1, ifelse(CatDatasetCreat$FLUTD == "No", 0,2))
CatDatasetCreat$PrevUO <- ifelse(CatDatasetCreat$PrevUO == "Yes", 1, ifelse(CatDatasetCreat$PrevUO == "No", 0,2))
CatDatasetCreat$HospUO <- ifelse(CatDatasetCreat$HospUO == "Yes", 1, ifelse(CatDatasetCreat$HospUO == "No", 0,2))
CatDatasetCreat$Flush <- ifelse(CatDatasetCreat$Flush == "Yes", 1, ifelse(CatDatasetCreat$Flush == "No", 0,2))
CatDatasetCreat$cathSize <- ifelse(CatDatasetCreat$cathSize == "Slippery sam", "3.5", ifelse(CatDatasetCreat$cathSize == "3.5", "3.5", 5))
CatDatasetCreat$Bolus <- ifelse(CatDatasetCreat$Bolus== "Yes", 1, ifelse(CatDatasetCreat$Bolus == "No", 0,2))
CatDatasetCreat$cathSize<- as.factor(CatDatasetCreat$cathSize)
CatDatasetCreat
```

```{r}
cat_data <- cats %>%
  select(Age, Weight..lbs., Breed, Diet, ER.Drugs., Difficulty, Time..min., Size.of.u.cath, Other.cath, Prescription.diet., Medications.after.dsg, Ketamine, Opioid, Isoflurane, Valium, Dexmedetomidine, Propofol, Water.Change, Environment.Change, Litter.Change, Signs.at.home, Repeat.UO.)  
```




