---
title: "Cat Project Analysis"
author: "Group-A: Olivia"
date: "2/19/25"
output:
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r, setup, include=FALSE}
require(dplyr)
require(mosaic)   # Load additional packages here 
require(Amelia)
library(ggplot2)
library(tidyr)
library(kableExtra)

# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

```{r}
cats <- read.csv("http://pmatheson.people.amherst.edu/CatsSet.csv")
```

``` {r}
#Get rid of pesky NA's in quantitative sets and replace with the average
cats$Age[is.na(cats$Age)] <- mean(cats$Age,na.rm=T)
cats$Weight..lbs.[is.na(cats$Weight..lbs.)] <- mean(cats$Weight..lbs.,na.rm=T)
cats$pH[is.na(cats$pH)] <- mean(cats$pH,na.rm=T)
cats$BG[is.na(cats$BG)] <- mean(cats$BG,na.rm=T)
cats$iCa[is.na(cats$iCa)] <- mean(cats$iCa,na.rm=T)
cats$K[is.na(cats$K)] <- mean(cats$K,na.rm=T)
cats$Lac[is.na(cats$Lac)] <- mean(cats$Lac,na.rm=T)
cats$BUN[is.na(cats$BUN)] <- mean(cats$BUN,na.rm=T)
cats$Creat[is.na(cats$Creat)] <- mean(cats$Creat,na.rm=T)
cats$TS[(cats$TS)=="No bloodwork"] <- NA
cats$PCV[(cats$PCV)=="No bloodwork"] <- NA
cats$TS[(cats$TS)==""] <- NA
cats$PCV[(cats$PCV)==""] <- NA
cats$PCV<-as.numeric(cats$PCV)
cats$TS<-as.numeric(cats$TS)
cats$PCV[is.na(cats$PCV)] <- mean(cats$PCV,na.rm=T)
cats$TS[is.na(cats$TS)] <- mean(cats$TS,na.rm=T)
cats$Temp[is.na(cats$Temp)] <- mean(cats$Temp,na.rm=T)
cats$HR[is.na(cats$HR)] <- mean(cats$HR,na.rm=T)
cats$Urine.protein[(cats$Urine.protein)=="Not checked"] <- NA
cats$Urine.protein<-as.numeric(cats$Urine.protein)
cats$Urine.protein[is.na(cats$Urine.protein)] <- mean(cats$Urine.protein,na.rm=T)
cats$USG[(cats$USG)=="Not checked"] <- NA
cats$USG<-as.numeric(cats$USG)
cats$USG[is.na(cats$USG)] <- mean(cats$USG,na.rm=T)
cats$Urine.pH[(cats$Urine.protein)=="Not checked"] <- NA
cats$Urine.pH<-as.numeric(cats$Urine.pH)
cats$Urine.pH[is.na(cats$Urine.pH)] <- mean(cats$Urine.pH,na.rm=T)

cats$Diet[(cats$Diet=="DRY")] <- "Dry"
cats$Diet[(cats$Diet=="Unknown")] <- "Dry"
cats$Access.to.outdoors.[(cats$Access.to.outdoors.=="Unknonw")] <- "No"
cats$Access.to.outdoors.[(cats$Access.to.outdoors.=="Unknown")] <- "No"
cats$Stress[(cats$Stress=="Unknown")] <- "No"
cats$Previous.FLUTD.signs.[(cats$Previous.FLUTD.signs.=="Unknown")] <- "Yes"
cats$Vx.[(cats$Vx.=="Unknown")] <- "Yes"
cats$PMHx[(cats$PMHx=="Unknown")] <- "No"

cats$Size.of.u.cath[(cats$Size.of.u.cath=="Slippery Sam")] <- 3.5
cats$Flush.[(cats$Flush.=="Unknown")] <- "Yes"
cats$Bolus.[(cats$bolus=="Unknown")] <- "Yes"
cats$Severe.illness.[(cats$Severe.illness.=="Undetermined")] <- "No"

cats$Anemia.[(cats$Anemia.=="Not checked")] <- "No"
cats$Became.anemic.[(cats$Became.anemic.=="Not rechecked")] <- "No"
cats$Became.anemic.[(cats$Became.anemic.=="No bloodwork")] <- "No"
cats$Crystals[(cats$Crystals=="Not checked")] <- "Yes"
cats$Urine.WBC[(cats$Urine.WBC=="Not checked")] <- NA
cats$Urine.RBC[(cats$Urine.RBC=="Not checked")] <- NA


data2<-na.omit(cats) #work with this data - doesn't have any N/As

```

```{r}
CatDatasetCreat <- cats %>%
  mutate(Ket = ifelse(Ketamine== "Yes", 1, 0)) %>%
  mutate(Val = ifelse(Valium=="Yes", 1, 0)) %>%
  mutate(Opi = ifelse(Opioid== "Yes", 1, 0)) %>%
  mutate(Dex = ifelse(Dexmedetomidine=="Yes", 1, 0)) %>%
  mutate(Iso = ifelse(Isoflurane=="Yes", 1, 0)) %>%
  mutate(Prop = ifelse(Propofol=="Yes", 1, 0)) %>%
  rename(RepeatUO="Repeat.UO.")%>%
  rename(Survival30="Survival.30.day")%>%
  rename(FLUTD="Previous.FLUTD.signs.")%>%
  rename(HospUO="Re.UO.in.hosp")%>%
  rename(PrevUO="Previous.UO")%>%
  rename(Flush="Flush.")%>%
  rename(Bolus="Bolus.")%>%
  rename(hrsCath="Hrs.of.cath")%>%
  rename(cathSize="Size.of.u.cath")%>%
  filter(!is.na(cathSize)) %>%
  filter(!is.na(  hrsCath)) %>%
  filter(!is.na( RepeatUO)) %>%
  filter(!is.na( Survival30)) %>%
  filter(!is.na( FLUTD)) %>%
  filter(!is.na( PrevUO)) %>%
  filter(!is.na( Flush)) %>%
  filter(!is.na(Bolus)) %>%
  filter(!is.na( HospUO )) %>%
  select(cathSize,  hrsCath, RepeatUO, Survival30, FLUTD, PrevUO, Flush, Bolus, HospUO ,Ket, Val, Opi, Dex, Iso, Prop)
CatDatasetCreat$RepeatUO <- ifelse(CatDatasetCreat$RepeatUO == "Yes", 1, ifelse(CatDatasetCreat$RepeatUO == "No", 0,2))
CatDatasetCreat$Survival30 <- ifelse(CatDatasetCreat$Survival30 == "Yes", 1, ifelse(CatDatasetCreat$Survival30 == "No", 0,2))
CatDatasetCreat$FLUTD <- ifelse(CatDatasetCreat$FLUTD == "Yes", 1, ifelse(CatDatasetCreat$FLUTD == "No", 0,2))
CatDatasetCreat$PrevUO <- ifelse(CatDatasetCreat$PrevUO == "Yes", 1, ifelse(CatDatasetCreat$PrevUO == "No", 0,2))
CatDatasetCreat$HospUO <- ifelse(CatDatasetCreat$HospUO == "Yes", 1, ifelse(CatDatasetCreat$HospUO == "No", 0,2))
CatDatasetCreat$Flush <- ifelse(CatDatasetCreat$Flush == "Yes", 1, ifelse(CatDatasetCreat$Flush == "No", 0,2))
CatDatasetCreat$cathSize <- ifelse(CatDatasetCreat$cathSize == "Slippery sam", "3.5", ifelse(CatDatasetCreat$cathSize == "3.5", "3.5", 5))
CatDatasetCreat$Bolus <- ifelse(CatDatasetCreat$Bolus== "Yes", 1, ifelse(CatDatasetCreat$Bolus == "No", 0,2))
CatDatasetCreat$cathSize<- as.factor(CatDatasetCreat$cathSize)
CatDatasetCreat
```

```{r}
cat_data <- cats %>%
  select(Age, Weight..lbs., Breed, Diet, ER.Drugs., Difficulty, Time..min., Size.of.u.cath, Other.cath, Prescription.diet., Medications.after.dsg, Ketamine, Opioid, Isoflurane, Valium, Dexmedetomidine, Propofol, Water.Change, Environment.Change, Litter.Change, Signs.at.home, Repeat.UO., Survival.30.day, Readmit., Prolonged.signs.)

# Diet as a Pie Chart
cat_data_diet <- cats %>%
  select(Diet) %>%
  na.omit() 
diet_counts <- cat_data_diet %>%
  group_by(Diet) %>%
  tally() %>%
  mutate(percentage = n / sum(n) * 100)

ggplot(diet_counts, aes(x = "", y = n, fill = Diet)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +  # Converts the bar chart into a pie chart
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_stack(vjust = 0.5)) +  # Add percentage labels
  labs(
    title = "Distribution of Diet Types",
    fill = "Diet"
  ) +
  theme_minimal() +
  theme(axis.text = element_blank(), axis.title = element_blank())

# filter out NAs
cat_data_diet <- cats %>%
  select(Diet, Repeat.UO.) %>%
  filter(!is.na(Diet), !is.na(Repeat.UO.))

# Visualize the distribution of RepeatUO by Diet
ggplot(cat_data_diet, aes(x = Diet, fill = factor(Repeat.UO.))) +
  geom_bar(position = "fill") + 
  labs(
    title = "Diet vs. Repeat UO",
    x = "Diet",
    y = "Proportion",
    fill = "Repeat UO"
  ) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_minimal()
```

```{r}
cat_data_prescription <- cats %>%
  select(Prescription.diet.) %>%
  na.omit() 
diet_counts <- cat_data_prescription %>%
  group_by(Prescription.diet.) %>%
  tally() %>%
  mutate(percentage = n / sum(n) * 100)

ggplot(diet_counts, aes(x = "", y = n, fill = Prescription.diet.)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +  # Converts the bar chart into a pie chart
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_stack(vjust = 0.5)) +  # Add percentage labels
  labs(
    title = "Distribution of Cats Who Received Prescription Diet",
    fill = "Diet"
  ) +
  theme_minimal() +
  theme(axis.text = element_blank(), axis.title = element_blank())

# filter out NAs
cat_data_prescription <- cats %>%
  select(Prescription.diet., Repeat.UO.) %>%
  filter(!is.na(Prescription.diet.), !is.na(Repeat.UO.))

# Visualize the relationship between Prescription Diet and Repeat UO
ggplot(cat_data_prescription , aes(x = Prescription.diet., fill = factor(Repeat.UO.))) +
  geom_bar(position = "fill") +  
  labs(
    title = "Prescription Diet vs. Repeat UO",
    x = "Prescription Diet",
    y = "Proportion",
    fill = "Repeat UO"
  ) +
  scale_y_continuous(labels = scales::percent_format()) + 
  theme_minimal()
```

```{r}
# Reshape data into long format for better visualization
cat_data_urine_symptoms <- cats %>%
  select(Repeat.UO., Strainguria, Hematuria, Lethargy, Pollakiuria) %>%
  pivot_longer(cols = -Repeat.UO., names_to = "Symptom", values_to = "Presence") %>%
  na.omit()

ggplot(cat_data_urine_symptoms, aes(x = Symptom, fill = factor(Presence))) +
  geom_bar(position = "fill") +
  facet_wrap(~Repeat.UO.) +  # Separate panels for Repeat UO Yes/No
  labs(
    title = "Urinary Symptoms and Return UO",
    x = "Urinary Symptoms",
    y = "Proportion",
    fill = "Symptom Present"
  ) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
cat_data_size <- cats %>%
  select(Repeat.UO., Size.of.u.cath) %>%
  pivot_longer(cols = -Repeat.UO., names_to = "Symptom", values_to = "Presence") %>%
  na.omit()

# Stacked bar chart showing proportion of cats with symptoms by Return UO status
ggplot(cat_data_size, aes(x = Symptom, fill = factor(Presence))) +
  geom_bar(position = "fill") +
  facet_wrap(~Repeat.UO.) +  # Separate panels for Repeat UO Yes/No
  labs(
    title = "Urinary Symptoms and Return UO",
    x = "Urinary Symptoms",
    y = "Proportion",
    fill = "Symptom Present"
  ) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r echo=FALSE}
catdatachange <- cat_data %>%
  select(Water.Change, Environment.Change, Litter.Change, Repeat.UO.) %>%
  pivot_longer(cols = -Repeat.UO., names_to = "Change", values_to = "Presence") %>%
  filter(Presence %in% c("Yes", "No"))%>%
  na.omit()%>%
  mutate(Change = recode(Change, 
                              "Environment.Change" = "Environmental Change", 
                              "Litter.Change" = "Litter Change", 
                              "Water.Change" = "Water Change"))

# Stacked bar chart showing proportion of cats with change by Return UO status
ggplot(catdatachange, aes(x = Change, fill = factor(Presence))) +
  geom_bar(position = "fill") +
  facet_wrap(~Repeat.UO., labeller = labeller(Repeat.UO. = c("No" = "Change Not Present", "Yes" = "Change Present"))) +  
  labs(
    title = "At Home Changes and Return UO",
    x = "Types of Changes",
    y = "Proportion of Repeat Urinary Infection in Cats",
    fill = "Repeat UO"
  ) +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(
    values = c("No" = "blue", " NO" = "blue", "no" = "blue", "Yes" = "red"), 
    labels = c("No" = "No", " No " = "No", "No  " = "No", "Yes" = "Yes")
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```



```{r}
catsignsathome <- cats %>%
  select(Signs.at.home) %>%
  filter(Signs.at.home %in% c("Yes", "No"))%>%
  na.omit() 
signs_counts <- catsignsathome %>%
  group_by(Signs.at.home) %>%
  tally() %>%
  mutate(percentage = n / sum(n) * 100)

ggplot(signs_counts, aes(x = "", y = n, fill = Signs.at.home)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +  # Converts the bar chart into a pie chart
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_stack(vjust = 0.5)) +  # Add percentage labels
  labs(
    title = "Distribution of Cats Who Received Had One Change At Home",
    fill = "Change Present"
  ) +
  scale_fill_manual(
    values = c("No" = "red", "Yes" = "purple"), 
    labels = c("No" = "No", "Yes" = "Yes")
  ) +
  theme_minimal() +
  theme(axis.text = element_blank(), axis.title = element_blank())

catsignstouo <- cats %>%
  select(Signs.at.home, Repeat.UO.) %>%
  filter(Signs.at.home %in% c("Yes", "No"))%>%
  na.omit()

# Visualize the relationship between Prescription Diet and Repeat UO
ggplot(catsignstouo , aes(x = Signs.at.home, fill = factor(Repeat.UO.))) +
  geom_bar(position = "fill") +  
  labs(
    title = "Changes At Home vs. Repeat UO",
    x = "Changes At Home",
    y = "Proportion",
    fill = "Repeat UO"
  ) +
  scale_y_continuous(labels = scales::percent_format()) + 
  theme_minimal()
```



```{r}
catsrepeatproblems <- cat_data %>%
  mutate(Any_Yes = if_else(Repeat.UO. == "Yes" | Survival.30.day == "No" | Readmit. == "Yes", "Yes", "No"))

# Create frequency table
anyproblems <- catsrepeatproblems %>%
  group_by(Any_Yes) %>%
  summarise(Frequency = n())%>%
  na.omit()

# Plot frequency table as a bar chart
ggplot(anyproblems, aes(x = Any_Yes, y = Frequency, fill = Any_Yes)) +
  geom_bar(stat = "identity") +
  labs(title = "Any Issues After Procedure",
       x = "Problem Present",
       y = "Frequency") +
  theme_minimal()

freq_table <- catsrepeatproblems %>%
  count(Any_Yes) %>%
  mutate(Percentage = round(n / sum(n) * 100, 1))

# Display the table
kable(freq_table, col.names = c("Category", "Count", "Percentage (%)"))
```


```{r}

```


```{r}
# Filter data to include only cases where Any_Yes is "Yes"
cat_data_yes <- catsrepeatproblems %>%
  filter(Any_Yes == "Yes") %>%
  select(Environment.Change, Litter.Change, Water.Change) %>%
  pivot_longer(cols = everything(), names_to = "Change_Type", values_to = "Change_Present") %>%
  filter(Change_Present %in% c("Yes", "No"))%>%
  na.omit()

# Create a bar chart for distribution of changes at home when Any_Yes is "Yes"
ggplot(cat_data_yes, aes(x = Change_Type, fill = Change_Present)) +
  geom_bar(position = "fill") +  # Normalize bars to show proportions
  labs(
    title = "Distribution of Changes at Home When Problems are Present",
    x = "Type of Change at Home",
    y = "Proportion",
    fill = "Change Present"
  ) +
  scale_y_continuous(labels = scales::percent_format()) +  # Show percentage
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```